version: '3.8'

services:
  # Сервис URL Shortener
  shortener:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=:8080
      - BASE_URL=http://localhost:8080
      - DATABASE_DSN=postgres://postgres:password@db:5432/shortener?sslmode=disable
    depends_on:
      - db
    restart: unless-stopped

  # Сервис авторизации
  auth:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SERVER_ADDRESS=:8082
      - DATABASE_DSN=postgres://postgres:password@db:5432/shortener?sslmode=disable
      - JWT_SECRET=supersecretkey
      - REFRESH_TOKEN_TTL=720
    depends_on:
      - db
    restart: unless-stopped

  # Сервис базы данных PostgreSQL
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=shortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Сервис pgAdmin для управления базой данных (опционально)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  