// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vitalykrupin/url-shortener.git/internal/app/storage (interfaces: StorageKeeper)

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorageKeeper is a mock of StorageKeeper interface.
type MockStorageKeeper struct {
	ctrl     *gomock.Controller
	recorder *MockStorageKeeperMockRecorder
}

// MockStorageKeeperMockRecorder is the mock recorder for MockStorageKeeper.
type MockStorageKeeperMockRecorder struct {
	mock *MockStorageKeeper
}

// NewMockStorageKeeper creates a new mock instance.
func NewMockStorageKeeper(ctrl *gomock.Controller) *MockStorageKeeper {
	mock := &MockStorageKeeper{ctrl: ctrl}
	mock.recorder = &MockStorageKeeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageKeeper) EXPECT() *MockStorageKeeperMockRecorder {
	return m.recorder
}

// AddToMemoryStore mocks base method.
func (m *MockStorageKeeper) AddToMemoryStore(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddToMemoryStore", arg0, arg1)
}

// AddToMemoryStore indicates an expected call of AddToMemoryStore.
func (mr *MockStorageKeeperMockRecorder) AddToMemoryStore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToMemoryStore", reflect.TypeOf((*MockStorageKeeper)(nil).AddToMemoryStore), arg0, arg1)
}

// GetAlias mocks base method.
func (m *MockStorageKeeper) GetAlias(arg0 string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlias", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetAlias indicates an expected call of GetAlias.
func (mr *MockStorageKeeperMockRecorder) GetAlias(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlias", reflect.TypeOf((*MockStorageKeeper)(nil).GetAlias), arg0)
}

// GetURL mocks base method.
func (m *MockStorageKeeper) GetURL(arg0 string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockStorageKeeperMockRecorder) GetURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockStorageKeeper)(nil).GetURL), arg0)
}

// LoadJSONfromFS mocks base method.
func (m *MockStorageKeeper) LoadJSONfromFS(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadJSONfromFS", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadJSONfromFS indicates an expected call of LoadJSONfromFS.
func (mr *MockStorageKeeperMockRecorder) LoadJSONfromFS(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadJSONfromFS", reflect.TypeOf((*MockStorageKeeper)(nil).LoadJSONfromFS), arg0)
}

// SaveJSONtoFS mocks base method.
func (m *MockStorageKeeper) SaveJSONtoFS(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveJSONtoFS", arg0)
}

// SaveJSONtoFS indicates an expected call of SaveJSONtoFS.
func (mr *MockStorageKeeperMockRecorder) SaveJSONtoFS(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveJSONtoFS", reflect.TypeOf((*MockStorageKeeper)(nil).SaveJSONtoFS), arg0)
}
